### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/twitter-persona#33]
**Congratulations on finishing milestone 2!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

## 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}

- [x] The documentation for the test functions is missing. - **quality -5**

- [x] #35
**Comment:** 
All unit tests pass after those two fixes:
1. Missing comma in line 20 on [test_generate_word_cloud.py](http://test_generate_word_cloud.py/) causing a syntax error. 
2. The package requires downloading vader_lexicon using the nltk downloaded to run which is not documented in README. 

#### 1. Create project structure for the R project
rubric={mechanics:20}
 
- [x] The code of conduct is missing - **mechanics -2**. 

- [x] There isn't a `[CONTRIBUTING.md](http://contributing.md/)` file. This file will live in `.github` and it will create that folder if it does not already exist. Edit the boiler plate document this gives to to reflect your contribution strategy that your team has agreed upon.- **mechanics -2**. 
   

## 4. R package function specifications
rubric={quality:10}
Good Job!

## 5. Specific expectations for this milestone are:
rubric={mechanics:10}
Good Job!

## 6. Submission instructions
rubric={mechanics:10}
Good Job!

**Comment by Yurui-Feng** [comment]
Missing CODE_OF_CONDUCT and CONTRIBUTING files added in https://github.com/UBC-MDS/twitterAnalysis/commit/13e6163cdcaa3b41b7ea66dd8b702c675d7eb626

**Comment by RenzoWijn** [comment]
Added documentation and fixed indentation and layout of test functions in both Python and R packages.
