### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/twitter-persona#38]
Congratulations on finishing milestone 3 group 2!  Nice work uploading your package to PYPI! Nice work on the Tests on R and setting up your R repo!  Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

Python Package

Great job passing CICD. 

Great job uploading to PYPI. It works!

Rstudio Package

- [x] Package dependency weren’t all put into the description file. You missed syuzhet. Mechanics -5

<img width="768" alt="Screenshot 2023-01-30 at 1 00 01 PM" src="https://user-images.githubusercontent.com/45893111/215596074-9d298d0d-0120-41ed-b829-5cd35867d893.png">

- [x] At least 1 test fails (3 tests failed) - -10 accuracy

<img width="950" alt="Screenshot 2023-01-30 at 1 03 06 PM" src="https://user-images.githubusercontent.com/45893111/215596089-1354171f-646a-47fe-9613-001f83923161.png">

- [x] The code of conduct is missing - mechanics -3.

- [x] There isn't a [CONTRIBUTING.md](http://contributing.md/) file. This file will live in .github and it will create that folder if it does not already exist. Edit the boiler plate document this gives to to reflect your contribution strategy that your team has agreed upon.- mechanics -3.

Great job, you’re at the final stretch. One milestone left :)

**Comment by andytai7** [comment]
<img width="979" alt="Screenshot 2023-02-04 at 2 41 47 PM" src="https://user-images.githubusercontent.com/45893111/216792508-68477d6d-12c4-485e-8c2c-213f799e5f29.png">

As you can tell here there is no github folder for milestone 3, with the contributing file. 

Additional marks were taken off since this was asked to be done from milestone 2 by TAs.
